require("dotenv").config({ path: "../.env" });
const mongoose = require("mongoose");
const Problem = require("../models/Problem");
const User = require("../models/User");

const problemsData = [
	// LeetCode Problems (70 problems)
	{
		title: "Two Sum",
		platform: "leetcode",
		problemId: "1",
		url: "https://leetcode.com/problems/two-sum/",
		difficulty: "easy",
		tags: ["array", "hash-table"],
		rating: 1200,
	},
	{
		title: "Add Two Numbers",
		platform: "leetcode",
		problemId: "2",
		url: "https://leetcode.com/problems/add-two-numbers/",
		difficulty: "medium",
		tags: ["linked-list", "math", "recursion"],
		rating: 1400,
	},
	{
		title: "Longest Substring Without Repeating Characters",
		platform: "leetcode",
		problemId: "3",
		url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
		difficulty: "medium",
		tags: ["string", "sliding-window", "hash-table"],
		rating: 1500,
	},
	{
		title: "Median of Two Sorted Arrays",
		platform: "leetcode",
		problemId: "4",
		url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
		difficulty: "hard",
		tags: ["array", "binary-search", "divide-and-conquer"],
		rating: 2100,
	},
	{
		title: "Longest Palindromic Substring",
		platform: "leetcode",
		problemId: "5",
		url: "https://leetcode.com/problems/longest-palindromic-substring/",
		difficulty: "medium",
		tags: ["string", "dynamic-programming"],
		rating: 1600,
	},
	{
		title: "Zigzag Conversion",
		platform: "leetcode",
		problemId: "6",
		url: "https://leetcode.com/problems/zigzag-conversion/",
		difficulty: "medium",
		tags: ["string"],
		rating: 1300,
	},
	{
		title: "Reverse Integer",
		platform: "leetcode",
		problemId: "7",
		url: "https://leetcode.com/problems/reverse-integer/",
		difficulty: "medium",
		tags: ["math"],
		rating: 1200,
	},
	{
		title: "String to Integer (atoi)",
		platform: "leetcode",
		problemId: "8",
		url: "https://leetcode.com/problems/string-to-integer-atoi/",
		difficulty: "medium",
		tags: ["string"],
		rating: 1400,
	},
	{
		title: "Palindrome Number",
		platform: "leetcode",
		problemId: "9",
		url: "https://leetcode.com/problems/palindrome-number/",
		difficulty: "easy",
		tags: ["math"],
		rating: 1100,
	},
	{
		title: "Regular Expression Matching",
		platform: "leetcode",
		problemId: "10",
		url: "https://leetcode.com/problems/regular-expression-matching/",
		difficulty: "hard",
		tags: ["string", "dynamic-programming", "recursion"],
		rating: 2200,
	},
	{
		title: "Container With Most Water",
		platform: "leetcode",
		problemId: "11",
		url: "https://leetcode.com/problems/container-with-most-water/",
		difficulty: "medium",
		tags: ["array", "two-pointers", "greedy"],
		rating: 1500,
	},
	{
		title: "Integer to Roman",
		platform: "leetcode",
		problemId: "12",
		url: "https://leetcode.com/problems/integer-to-roman/",
		difficulty: "medium",
		tags: ["hash-table", "math", "string"],
		rating: 1300,
	},
	{
		title: "Roman to Integer",
		platform: "leetcode",
		problemId: "13",
		url: "https://leetcode.com/problems/roman-to-integer/",
		difficulty: "easy",
		tags: ["hash-table", "math", "string"],
		rating: 1100,
	},
	{
		title: "Longest Common Prefix",
		platform: "leetcode",
		problemId: "14",
		url: "https://leetcode.com/problems/longest-common-prefix/",
		difficulty: "easy",
		tags: ["string"],
		rating: 1100,
	},
	{
		title: "3Sum",
		platform: "leetcode",
		problemId: "15",
		url: "https://leetcode.com/problems/3sum/",
		difficulty: "medium",
		tags: ["array", "two-pointers", "sorting"],
		rating: 1600,
	},
	{
		title: "Letter Combinations of a Phone Number",
		platform: "leetcode",
		problemId: "17",
		url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
		difficulty: "medium",
		tags: ["hash-table", "string", "backtracking"],
		rating: 1400,
	},
	{
		title: "Remove Nth Node From End of List",
		platform: "leetcode",
		problemId: "19",
		url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
		difficulty: "medium",
		tags: ["linked-list", "two-pointers"],
		rating: 1400,
	},
	{
		title: "Valid Parentheses",
		platform: "leetcode",
		problemId: "20",
		url: "https://leetcode.com/problems/valid-parentheses/",
		difficulty: "easy",
		tags: ["string", "stack"],
		rating: 1200,
	},
	{
		title: "Merge Two Sorted Lists",
		platform: "leetcode",
		problemId: "21",
		url: "https://leetcode.com/problems/merge-two-sorted-lists/",
		difficulty: "easy",
		tags: ["linked-list", "recursion"],
		rating: 1200,
	},
	{
		title: "Generate Parentheses",
		platform: "leetcode",
		problemId: "22",
		url: "https://leetcode.com/problems/generate-parentheses/",
		difficulty: "medium",
		tags: ["string", "dynamic-programming", "backtracking"],
		rating: 1600,
	},
	{
		title: "Merge k Sorted Lists",
		platform: "leetcode",
		problemId: "23",
		url: "https://leetcode.com/problems/merge-k-sorted-lists/",
		difficulty: "hard",
		tags: ["linked-list", "divide-and-conquer", "heap"],
		rating: 1900,
	},
	{
		title: "Swap Nodes in Pairs",
		platform: "leetcode",
		problemId: "24",
		url: "https://leetcode.com/problems/swap-nodes-in-pairs/",
		difficulty: "medium",
		tags: ["linked-list", "recursion"],
		rating: 1400,
	},
	{
		title: "Reverse Nodes in k-Group",
		platform: "leetcode",
		problemId: "25",
		url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
		difficulty: "hard",
		tags: ["linked-list", "recursion"],
		rating: 2000,
	},
	{
		title: "Remove Duplicates from Sorted Array",
		platform: "leetcode",
		problemId: "26",
		url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
		difficulty: "easy",
		tags: ["array", "two-pointers"],
		rating: 1100,
	},
	{
		title: "Implement strStr()",
		platform: "leetcode",
		problemId: "28",
		url: "https://leetcode.com/problems/implement-strstr/",
		difficulty: "easy",
		tags: ["string", "two-pointers"],
		rating: 1200,
	},
	{
		title: "Divide Two Integers",
		platform: "leetcode",
		problemId: "29",
		url: "https://leetcode.com/problems/divide-two-integers/",
		difficulty: "medium",
		tags: ["math", "bit-manipulation"],
		rating: 1600,
	},
	{
		title: "Next Permutation",
		platform: "leetcode",
		problemId: "31",
		url: "https://leetcode.com/problems/next-permutation/",
		difficulty: "medium",
		tags: ["array", "two-pointers"],
		rating: 1500,
	},
	{
		title: "Longest Valid Parentheses",
		platform: "leetcode",
		problemId: "32",
		url: "https://leetcode.com/problems/longest-valid-parentheses/",
		difficulty: "hard",
		tags: ["string", "dynamic-programming", "stack"],
		rating: 2100,
	},
	{
		title: "Search in Rotated Sorted Array",
		platform: "leetcode",
		problemId: "33",
		url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
		difficulty: "medium",
		tags: ["array", "binary-search"],
		rating: 1600,
	},
	{
		title: "Find First and Last Position of Element in Sorted Array",
		platform: "leetcode",
		problemId: "34",
		url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
		difficulty: "medium",
		tags: ["array", "binary-search"],
		rating: 1500,
	},
	{
		title: "Valid Sudoku",
		platform: "leetcode",
		problemId: "36",
		url: "https://leetcode.com/problems/valid-sudoku/",
		difficulty: "medium",
		tags: ["array", "hash-table", "matrix"],
		rating: 1400,
	},
	{
		title: "Sudoku Solver",
		platform: "leetcode",
		problemId: "37",
		url: "https://leetcode.com/problems/sudoku-solver/",
		difficulty: "hard",
		tags: ["array", "backtracking", "matrix"],
		rating: 2000,
	},
	{
		title: "Count and Say",
		platform: "leetcode",
		problemId: "38",
		url: "https://leetcode.com/problems/count-and-say/",
		difficulty: "medium",
		tags: ["string"],
		rating: 1300,
	},
	{
		title: "Combination Sum",
		platform: "leetcode",
		problemId: "39",
		url: "https://leetcode.com/problems/combination-sum/",
		difficulty: "medium",
		tags: ["array", "backtracking"],
		rating: 1500,
	},
	{
		title: "Combination Sum II",
		platform: "leetcode",
		problemId: "40",
		url: "https://leetcode.com/problems/combination-sum-ii/",
		difficulty: "medium",
		tags: ["array", "backtracking"],
		rating: 1600,
	},
	{
		title: "First Missing Positive",
		platform: "leetcode",
		problemId: "41",
		url: "https://leetcode.com/problems/first-missing-positive/",
		difficulty: "hard",
		tags: ["array", "hash-table"],
		rating: 2000,
	},
	{
		title: "Trapping Rain Water",
		platform: "leetcode",
		problemId: "42",
		url: "https://leetcode.com/problems/trapping-rain-water/",
		difficulty: "hard",
		tags: ["array", "two-pointers", "dynamic-programming", "stack"],
		rating: 2100,
	},
	{
		title: "Multiply Strings",
		platform: "leetcode",
		problemId: "43",
		url: "https://leetcode.com/problems/multiply-strings/",
		difficulty: "medium",
		tags: ["math", "string", "simulation"],
		rating: 1500,
	},
	{
		title: "Wildcard Matching",
		platform: "leetcode",
		problemId: "44",
		url: "https://leetcode.com/problems/wildcard-matching/",
		difficulty: "hard",
		tags: ["string", "dynamic-programming", "greedy", "recursion"],
		rating: 2200,
	},
	{
		title: "Jump Game II",
		platform: "leetcode",
		problemId: "45",
		url: "https://leetcode.com/problems/jump-game-ii/",
		difficulty: "medium",
		tags: ["array", "dynamic-programming", "greedy"],
		rating: 1700,
	},
	{
		title: "Permutations",
		platform: "leetcode",
		problemId: "46",
		url: "https://leetcode.com/problems/permutations/",
		difficulty: "medium",
		tags: ["array", "backtracking"],
		rating: 1500,
	},
	{
		title: "Permutations II",
		platform: "leetcode",
		problemId: "47",
		url: "https://leetcode.com/problems/permutations-ii/",
		difficulty: "medium",
		tags: ["array", "backtracking"],
		rating: 1600,
	},
	{
		title: "Rotate Image",
		platform: "leetcode",
		problemId: "48",
		url: "https://leetcode.com/problems/rotate-image/",
		difficulty: "medium",
		tags: ["array", "math", "matrix"],
		rating: 1500,
	},
	{
		title: "Group Anagrams",
		platform: "leetcode",
		problemId: "49",
		url: "https://leetcode.com/problems/group-anagrams/",
		difficulty: "medium",
		tags: ["array", "hash-table", "string", "sorting"],
		rating: 1500,
	},
	{
		title: "Pow(x, n)",
		platform: "leetcode",
		problemId: "50",
		url: "https://leetcode.com/problems/powx-n/",
		difficulty: "medium",
		tags: ["math", "recursion"],
		rating: 1400,
	},
	{
		title: "N-Queens",
		platform: "leetcode",
		problemId: "51",
		url: "https://leetcode.com/problems/n-queens/",
		difficulty: "hard",
		tags: ["array", "backtracking"],
		rating: 2000,
	},
	{
		title: "Maximum Subarray",
		platform: "leetcode",
		problemId: "53",
		url: "https://leetcode.com/problems/maximum-subarray/",
		difficulty: "medium",
		tags: ["array", "divide-and-conquer", "dynamic-programming"],
		rating: 1500,
	},
	{
		title: "Spiral Matrix",
		platform: "leetcode",
		problemId: "54",
		url: "https://leetcode.com/problems/spiral-matrix/",
		difficulty: "medium",
		tags: ["array", "matrix", "simulation"],
		rating: 1500,
	},
	{
		title: "Jump Game",
		platform: "leetcode",
		problemId: "55",
		url: "https://leetcode.com/problems/jump-game/",
		difficulty: "medium",
		tags: ["array", "dynamic-programming", "greedy"],
		rating: 1600,
	},
	{
		title: "Merge Intervals",
		platform: "leetcode",
		problemId: "56",
		url: "https://leetcode.com/problems/merge-intervals/",
		difficulty: "medium",
		tags: ["array", "sorting"],
		rating: 1600,
	},
	{
		title: "Insert Interval",
		platform: "leetcode",
		problemId: "57",
		url: "https://leetcode.com/problems/insert-interval/",
		difficulty: "medium",
		tags: ["array"],
		rating: 1600,
	},
	{
		title: "Length of Last Word",
		platform: "leetcode",
		problemId: "58",
		url: "https://leetcode.com/problems/length-of-last-word/",
		difficulty: "easy",
		tags: ["string"],
		rating: 1000,
	},
	{
		title: "Spiral Matrix II",
		platform: "leetcode",
		problemId: "59",
		url: "https://leetcode.com/problems/spiral-matrix-ii/",
		difficulty: "medium",
		tags: ["array", "matrix", "simulation"],
		rating: 1500,
	},
	{
		title: "Permutation Sequence",
		platform: "leetcode",
		problemId: "60",
		url: "https://leetcode.com/problems/permutation-sequence/",
		difficulty: "hard",
		tags: ["math", "recursion"],
		rating: 1900,
	},
	{
		title: "Rotate List",
		platform: "leetcode",
		problemId: "61",
		url: "https://leetcode.com/problems/rotate-list/",
		difficulty: "medium",
		tags: ["linked-list", "two-pointers"],
		rating: 1400,
	},
	{
		title: "Unique Paths",
		platform: "leetcode",
		problemId: "62",
		url: "https://leetcode.com/problems/unique-paths/",
		difficulty: "medium",
		tags: ["math", "dynamic-programming", "combinatorics"],
		rating: 1500,
	},
	{
		title: "Unique Paths II",
		platform: "leetcode",
		problemId: "63",
		url: "https://leetcode.com/problems/unique-paths-ii/",
		difficulty: "medium",
		tags: ["array", "dynamic-programming", "matrix"],
		rating: 1500,
	},
	{
		title: "Minimum Path Sum",
		platform: "leetcode",
		problemId: "64",
		url: "https://leetcode.com/problems/minimum-path-sum/",
		difficulty: "medium",
		tags: ["array", "dynamic-programming", "matrix"],
		rating: 1500,
	},
	{
		title: "Valid Number",
		platform: "leetcode",
		problemId: "65",
		url: "https://leetcode.com/problems/valid-number/",
		difficulty: "hard",
		tags: ["string"],
		rating: 1800,
	},
	{
		title: "Plus One",
		platform: "leetcode",
		problemId: "66",
		url: "https://leetcode.com/problems/plus-one/",
		difficulty: "easy",
		tags: ["array", "math"],
		rating: 1100,
	},
	{
		title: "Add Binary",
		platform: "leetcode",
		problemId: "67",
		url: "https://leetcode.com/problems/add-binary/",
		difficulty: "easy",
		tags: ["math", "string", "bit-manipulation", "simulation"],
		rating: 1200,
	},
	{
		title: "Text Justification",
		platform: "leetcode",
		problemId: "68",
		url: "https://leetcode.com/problems/text-justification/",
		difficulty: "hard",
		tags: ["array", "string", "simulation"],
		rating: 2000,
	},
	{
		title: "Sqrt(x)",
		platform: "leetcode",
		problemId: "69",
		url: "https://leetcode.com/problems/sqrtx/",
		difficulty: "easy",
		tags: ["math", "binary-search"],
		rating: 1200,
	},
	{
		title: "Climbing Stairs",
		platform: "leetcode",
		problemId: "70",
		url: "https://leetcode.com/problems/climbing-stairs/",
		difficulty: "easy",
		tags: ["math", "dynamic-programming", "memoization"],
		rating: 1200,
	},
	{
		title: "Simplify Path",
		platform: "leetcode",
		problemId: "71",
		url: "https://leetcode.com/problems/simplify-path/",
		difficulty: "medium",
		tags: ["string", "stack"],
		rating: 1400,
	},
	{
		title: "Edit Distance",
		platform: "leetcode",
		problemId: "72",
		url: "https://leetcode.com/problems/edit-distance/",
		difficulty: "hard",
		tags: ["string", "dynamic-programming"],
		rating: 2000,
	},
	{
		title: "Set Matrix Zeroes",
		platform: "leetcode",
		problemId: "73",
		url: "https://leetcode.com/problems/set-matrix-zeroes/",
		difficulty: "medium",
		tags: ["array", "hash-table", "matrix"],
		rating: 1500,
	},
	{
		title: "Search a 2D Matrix",
		platform: "leetcode",
		problemId: "74",
		url: "https://leetcode.com/problems/search-a-2d-matrix/",
		difficulty: "medium",
		tags: ["array", "binary-search", "matrix"],
		rating: 1400,
	},
	{
		title: "Sort Colors",
		platform: "leetcode",
		problemId: "75",
		url: "https://leetcode.com/problems/sort-colors/",
		difficulty: "medium",
		tags: ["array", "two-pointers", "sorting"],
		rating: 1400,
	},

	// Codeforces Problems (65 problems)
	{
		title: "Watermelon",
		platform: "codeforces",
		problemId: "4A",
		url: "https://codeforces.com/problemset/problem/4/A",
		difficulty: "easy",
		tags: ["brute-force", "math"],
		rating: 800,
	},
	{
		title: "Theatre Square",
		platform: "codeforces",
		problemId: "1A",
		url: "https://codeforces.com/problemset/problem/1/A",
		difficulty: "easy",
		tags: ["math"],
		rating: 1000,
	},
	{
		title: "Way Too Long Words",
		platform: "codeforces",
		problemId: "71A",
		url: "https://codeforces.com/problemset/problem/71/A",
		difficulty: "easy",
		tags: ["strings"],
		rating: 800,
	},
	{
		title: "Team",
		platform: "codeforces",
		problemId: "231A",
		url: "https://codeforces.com/problemset/problem/231/A",
		difficulty: "easy",
		tags: ["brute-force", "greedy"],
		rating: 800,
	},
	{
		title: "Next Round",
		platform: "codeforces",
		problemId: "158A",
		url: "https://codeforces.com/problemset/problem/158/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Bit++",
		platform: "codeforces",
		problemId: "282A",
		url: "https://codeforces.com/problemset/problem/282/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Domino piling",
		platform: "codeforces",
		problemId: "50A",
		url: "https://codeforces.com/problemset/problem/50/A",
		difficulty: "easy",
		tags: ["greedy", "math"],
		rating: 800,
	},
	{
		title: "Beautiful Matrix",
		platform: "codeforces",
		problemId: "263A",
		url: "https://codeforces.com/problemset/problem/263/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Queue at the School",
		platform: "codeforces",
		problemId: "266B",
		url: "https://codeforces.com/problemset/problem/266/B",
		difficulty: "easy",
		tags: ["constructive-algorithms", "graph-matchings", "implementation"],
		rating: 800,
	},
	{
		title: "Borze",
		platform: "codeforces",
		problemId: "32B",
		url: "https://codeforces.com/problemset/problem/32/B",
		difficulty: "easy",
		tags: ["expression-parsing", "implementation"],
		rating: 800,
	},
	{
		title: "Beautiful Year",
		platform: "codeforces",
		problemId: "271A",
		url: "https://codeforces.com/problemset/problem/271/A",
		difficulty: "easy",
		tags: ["brute-force"],
		rating: 800,
	},
	{
		title: "Drinks",
		platform: "codeforces",
		problemId: "200B",
		url: "https://codeforces.com/problemset/problem/200/B",
		difficulty: "easy",
		tags: ["implementation", "math"],
		rating: 800,
	},
	{
		title: "Insomnia cure",
		platform: "codeforces",
		problemId: "148A",
		url: "https://codeforces.com/problemset/problem/148/A",
		difficulty: "easy",
		tags: ["constructive-algorithms", "implementation", "math"],
		rating: 800,
	},
	{
		title: "George and Accommodation",
		platform: "codeforces",
		problemId: "467A",
		url: "https://codeforces.com/problemset/problem/467/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Tram",
		platform: "codeforces",
		problemId: "116A",
		url: "https://codeforces.com/problemset/problem/116/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Young Physicist",
		platform: "codeforces",
		problemId: "69A",
		url: "https://codeforces.com/problemset/problem/69/A",
		difficulty: "easy",
		tags: ["implementation", "math"],
		rating: 1000,
	},
	{
		title: "Nearly Lucky Number",
		platform: "codeforces",
		problemId: "110A",
		url: "https://codeforces.com/problemset/problem/110/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Stones on the Table",
		platform: "codeforces",
		problemId: "266A",
		url: "https://codeforces.com/problemset/problem/266/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Elephant",
		platform: "codeforces",
		problemId: "617A",
		url: "https://codeforces.com/problemset/problem/617/A",
		difficulty: "easy",
		tags: ["math"],
		rating: 800,
	},
	{
		title: "Twins",
		platform: "codeforces",
		problemId: "160A",
		url: "https://codeforces.com/problemset/problem/160/A",
		difficulty: "easy",
		tags: ["greedy", "sortings"],
		rating: 900,
	},
	{
		title: "I Wanna Be the Guy",
		platform: "codeforces",
		problemId: "469A",
		url: "https://codeforces.com/problemset/problem/469/A",
		difficulty: "easy",
		tags: ["greedy", "implementation"],
		rating: 800,
	},
	{
		title: "Word",
		platform: "codeforces",
		problemId: "59A",
		url: "https://codeforces.com/problemset/problem/59/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 800,
	},
	{
		title: "Word Capitalization",
		platform: "codeforces",
		problemId: "281A",
		url: "https://codeforces.com/problemset/problem/281/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 800,
	},
	{
		title: "Helpful Maths",
		platform: "codeforces",
		problemId: "339A",
		url: "https://codeforces.com/problemset/problem/339/A",
		difficulty: "easy",
		tags: ["greedy", "implementation", "sortings", "strings"],
		rating: 800,
	},
	{
		title: "Chat room",
		platform: "codeforces",
		problemId: "58A",
		url: "https://codeforces.com/problemset/problem/58/A",
		difficulty: "easy",
		tags: ["greedy", "strings"],
		rating: 1000,
	},
	{
		title: "Football",
		platform: "codeforces",
		problemId: "96A",
		url: "https://codeforces.com/problemset/problem/96/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 900,
	},
	{
		title: "Soldier and Bananas",
		platform: "codeforces",
		problemId: "546A",
		url: "https://codeforces.com/problemset/problem/546/A",
		difficulty: "easy",
		tags: ["brute-force", "implementation", "math"],
		rating: 800,
	},
	{
		title: "Bear and Big Brother",
		platform: "codeforces",
		problemId: "791A",
		url: "https://codeforces.com/problemset/problem/791/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Calculating Function",
		platform: "codeforces",
		problemId: "486A",
		url: "https://codeforces.com/problemset/problem/486/A",
		difficulty: "medium",
		tags: ["implementation", "math"],
		rating: 800,
	},
	{
		title: "Anton and Danik",
		platform: "codeforces",
		problemId: "734A",
		url: "https://codeforces.com/problemset/problem/734/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 800,
	},
	{
		title: "Wrong Subtraction",
		platform: "codeforces",
		problemId: "977A",
		url: "https://codeforces.com/problemset/problem/977/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Magnets",
		platform: "codeforces",
		problemId: "344A",
		url: "https://codeforces.com/problemset/problem/344/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Sereja and Dima",
		platform: "codeforces",
		problemId: "381A",
		url: "https://codeforces.com/problemset/problem/381/A",
		difficulty: "easy",
		tags: ["greedy", "implementation", "two-pointers"],
		rating: 800,
	},
	{
		title: "Even Odds",
		platform: "codeforces",
		problemId: "318A",
		url: "https://codeforces.com/problemset/problem/318/A",
		difficulty: "easy",
		tags: ["math"],
		rating: 900,
	},
	{
		title: "Maximum Increase",
		platform: "codeforces",
		problemId: "702A",
		url: "https://codeforces.com/problemset/problem/702/A",
		difficulty: "easy",
		tags: ["dp", "greedy", "implementation"],
		rating: 800,
	},
	{
		title: "Vanya and Fence",
		platform: "codeforces",
		problemId: "677A",
		url: "https://codeforces.com/problemset/problem/677/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Translation",
		platform: "codeforces",
		problemId: "41A",
		url: "https://codeforces.com/problemset/problem/41/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 900,
	},
	{
		title: "Ultra-Fast Mathematician",
		platform: "codeforces",
		problemId: "61A",
		url: "https://codeforces.com/problemset/problem/61/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 800,
	},
	{
		title: "Presents",
		platform: "codeforces",
		problemId: "136A",
		url: "https://codeforces.com/problemset/problem/136/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "In Search of an Easy Problem",
		platform: "codeforces",
		problemId: "1030A",
		url: "https://codeforces.com/problemset/problem/1030/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Vasya the Hipster",
		platform: "codeforces",
		problemId: "581A",
		url: "https://codeforces.com/problemset/problem/581/A",
		difficulty: "easy",
		tags: ["implementation", "math"],
		rating: 800,
	},
	{
		title: "Boy or Girl",
		platform: "codeforces",
		problemId: "236A",
		url: "https://codeforces.com/problemset/problem/236/A",
		difficulty: "easy",
		tags: ["brute-force", "implementation", "strings"],
		rating: 800,
	},
	{
		title: "Arrival of the General",
		platform: "codeforces",
		problemId: "144A",
		url: "https://codeforces.com/problemset/problem/144/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Divisibility Problem",
		platform: "codeforces",
		problemId: "1328A",
		url: "https://codeforces.com/problemset/problem/1328/A",
		difficulty: "easy",
		tags: ["math"],
		rating: 800,
	},
	{
		title: "Amusing Joke",
		platform: "codeforces",
		problemId: "141A",
		url: "https://codeforces.com/problemset/problem/141/A",
		difficulty: "easy",
		tags: ["implementation", "sortings", "strings"],
		rating: 800,
	},
	{
		title: "HQ9+",
		platform: "codeforces",
		problemId: "133A",
		url: "https://codeforces.com/problemset/problem/133/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 900,
	},
	{
		title: "Free Ice Cream",
		platform: "codeforces",
		problemId: "686A",
		url: "https://codeforces.com/problemset/problem/686/A",
		difficulty: "easy",
		tags: ["constructive-algorithms", "implementation"],
		rating: 900,
	},
	{
		title: "Square String?",
		platform: "codeforces",
		problemId: "1619A",
		url: "https://codeforces.com/problemset/problem/1619/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 800,
	},
	{
		title: "Design Tutorial: Learn from Math",
		platform: "codeforces",
		problemId: "472A",
		url: "https://codeforces.com/problemset/problem/472/A",
		difficulty: "easy",
		tags: ["math", "number-theory"],
		rating: 800,
	},
	{
		title: "Petya and Strings",
		platform: "codeforces",
		problemId: "112A",
		url: "https://codeforces.com/problemset/problem/112/A",
		difficulty: "easy",
		tags: ["implementation", "strings"],
		rating: 800,
	},
	{
		title: "Lucky Division",
		platform: "codeforces",
		problemId: "122A",
		url: "https://codeforces.com/problemset/problem/122/A",
		difficulty: "easy",
		tags: ["brute-force", "number-theory"],
		rating: 1000,
	},
	{
		title: "Fox And Snake",
		platform: "codeforces",
		problemId: "510A",
		url: "https://codeforces.com/problemset/problem/510/A",
		difficulty: "easy",
		tags: ["constructive-algorithms", "implementation"],
		rating: 800,
	},
	{
		title: "New Year Candles",
		platform: "codeforces",
		problemId: "379A",
		url: "https://codeforces.com/problemset/problem/379/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 1000,
	},
	{
		title: "Roma and Lucky Numbers",
		platform: "codeforces",
		problemId: "262A",
		url: "https://codeforces.com/problemset/problem/262/A",
		difficulty: "easy",
		tags: ["brute-force", "implementation"],
		rating: 900,
	},
	{
		title: "Kefa and First Steps",
		platform: "codeforces",
		problemId: "580A",
		url: "https://codeforces.com/problemset/problem/580/A",
		difficulty: "easy",
		tags: ["brute-force", "dp", "implementation"],
		rating: 900,
	},
	{
		title: "Is your horseshoe on the other hoof?",
		platform: "codeforces",
		problemId: "228A",
		url: "https://codeforces.com/problemset/problem/228/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Taxi",
		platform: "codeforces",
		problemId: "158B",
		url: "https://codeforces.com/problemset/problem/158/B",
		difficulty: "medium",
		tags: ["constructive-algorithms", "greedy", "implementation"],
		rating: 1100,
	},
	{
		title: "Dubstep",
		platform: "codeforces",
		problemId: "208A",
		url: "https://codeforces.com/problemset/problem/208/A",
		difficulty: "medium",
		tags: ["strings"],
		rating: 900,
	},
	{
		title: "Brain's Photos",
		platform: "codeforces",
		problemId: "707A",
		url: "https://codeforces.com/problemset/problem/707/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 800,
	},
	{
		title: "Police Recruits",
		platform: "codeforces",
		problemId: "427A",
		url: "https://codeforces.com/problemset/problem/427/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 900,
	},
	{
		title: "Gravity Flip",
		platform: "codeforces",
		problemId: "405A",
		url: "https://codeforces.com/problemset/problem/405/A",
		difficulty: "easy",
		tags: ["greedy", "implementation", "sortings"],
		rating: 900,
	},
	{
		title: "Lights Out",
		platform: "codeforces",
		problemId: "275A",
		url: "https://codeforces.com/problemset/problem/275/A",
		difficulty: "easy",
		tags: ["implementation"],
		rating: 900,
	},
	{
		title: "Anton and Letters",
		platform: "codeforces",
		problemId: "443A",
		url: "https://codeforces.com/problemset/problem/443/A",
		difficulty: "easy",
		tags: ["constructive-algorithms", "implementation"],
		rating: 800,
	},
	{
		title: "Die Roll",
		platform: "codeforces",
		problemId: "9A",
		url: "https://codeforces.com/problemset/problem/9/A",
		difficulty: "easy",
		tags: ["math", "probabilities"],
		rating: 800,
	},
	{
		title: "Games",
		platform: "codeforces",
		problemId: "268A",
		url: "https://codeforces.com/problemset/problem/268/A",
		difficulty: "easy",
		tags: ["brute-force"],
		rating: 800,
	},

	// CodeChef Problems (65 problems)
	{
		title: "ATM",
		platform: "codechef",
		problemId: "HS08TEST",
		url: "https://www.codechef.com/problems/HS08TEST",
		difficulty: "beginner",
		tags: ["simulation", "conditionals"],
		rating: 1000,
	},
	{
		title: "Add Two Numbers",
		platform: "codechef",
		problemId: "FLOW001",
		url: "https://www.codechef.com/problems/FLOW001",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Enormous Input Test",
		platform: "codechef",
		problemId: "INTEST",
		url: "https://www.codechef.com/problems/INTEST",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 900,
	},
	{
		title: "Number Mirror",
		platform: "codechef",
		problemId: "START01",
		url: "https://www.codechef.com/problems/START01",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Sum of Digits",
		platform: "codechef",
		problemId: "FLOW006",
		url: "https://www.codechef.com/problems/FLOW006",
		difficulty: "beginner",
		tags: ["basic-programming", "math"],
		rating: 800,
	},
	{
		title: "Find Remainder",
		platform: "codechef",
		problemId: "FLOW002",
		url: "https://www.codechef.com/problems/FLOW002",
		difficulty: "beginner",
		tags: ["basic-programming", "math"],
		rating: 800,
	},
	{
		title: "First and Last Digit",
		platform: "codechef",
		problemId: "FLOW004",
		url: "https://www.codechef.com/problems/FLOW004",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Reverse The Number",
		platform: "codechef",
		problemId: "FLOW007",
		url: "https://www.codechef.com/problems/FLOW007",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 900,
	},
	{
		title: "Lucky Four",
		platform: "codechef",
		problemId: "LUCKFOUR",
		url: "https://www.codechef.com/problems/LUCKFOUR",
		difficulty: "beginner",
		tags: ["basic-programming", "strings"],
		rating: 800,
	},
	{
		title: "Factorial",
		platform: "codechef",
		problemId: "FCTRL",
		url: "https://www.codechef.com/problems/FCTRL",
		difficulty: "easy",
		tags: ["math", "number-theory"],
		rating: 1200,
	},
	{
		title: "Small Factorials",
		platform: "codechef",
		problemId: "FCTRL2",
		url: "https://www.codechef.com/problems/FCTRL2",
		difficulty: "easy",
		tags: ["big-numbers", "factorization", "math"],
		rating: 1100,
	},
	{
		title: "Turbo Sort",
		platform: "codechef",
		problemId: "TSORT",
		url: "https://www.codechef.com/problems/TSORT",
		difficulty: "beginner",
		tags: ["sorting"],
		rating: 900,
	},
	{
		title: "The Lead Game",
		platform: "codechef",
		problemId: "TLG",
		url: "https://www.codechef.com/problems/TLG",
		difficulty: "beginner",
		tags: ["simulation"],
		rating: 900,
	},
	{
		title: "Lapindromes",
		platform: "codechef",
		problemId: "LAPIN",
		url: "https://www.codechef.com/problems/LAPIN",
		difficulty: "easy",
		tags: ["strings"],
		rating: 1000,
	},
	{
		title: "Total Expenses",
		platform: "codechef",
		problemId: "FLOW009",
		url: "https://www.codechef.com/problems/FLOW009",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Second Largest",
		platform: "codechef",
		problemId: "FLOW017",
		url: "https://www.codechef.com/problems/FLOW017",
		difficulty: "beginner",
		tags: ["basic-programming", "sorting"],
		rating: 900,
	},
	{
		title: "Id and Ship",
		platform: "codechef",
		problemId: "FLOW010",
		url: "https://www.codechef.com/problems/FLOW010",
		difficulty: "beginner",
		tags: ["conditionals"],
		rating: 800,
	},
	{
		title: "Valid Triangles",
		platform: "codechef",
		problemId: "FLOW013",
		url: "https://www.codechef.com/problems/FLOW013",
		difficulty: "beginner",
		tags: ["geometry", "math"],
		rating: 800,
	},
	{
		title: "Grade The Steel",
		platform: "codechef",
		problemId: "FLOW014",
		url: "https://www.codechef.com/problems/FLOW014",
		difficulty: "beginner",
		tags: ["conditionals"],
		rating: 900,
	},
	{
		title: "Discus Throw",
		platform: "codechef",
		problemId: "DISCUS",
		url: "https://www.codechef.com/problems/DISCUS",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Triangle Count",
		platform: "codechef",
		problemId: "TRICONT",
		url: "https://www.codechef.com/problems/TRICONT",
		difficulty: "easy",
		tags: ["combinatorics", "math"],
		rating: 1100,
	},
	{
		title: "Primality Test",
		platform: "codechef",
		problemId: "PRB01",
		url: "https://www.codechef.com/problems/PRB01",
		difficulty: "beginner",
		tags: ["number-theory"],
		rating: 900,
	},
	{
		title: "Baking Cakes",
		platform: "codechef",
		problemId: "CAKEWALK",
		url: "https://www.codechef.com/problems/CAKEWALK",
		difficulty: "beginner",
		tags: ["simulation"],
		rating: 800,
	},
	{
		title: "Chef and Operators",
		platform: "codechef",
		problemId: "CHOPRT",
		url: "https://www.codechef.com/problems/CHOPRT",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Life, the Universe, and Everything",
		platform: "codechef",
		problemId: "TEST",
		url: "https://www.codechef.com/problems/TEST",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Helping Chef",
		platform: "codechef",
		problemId: "FLOW008",
		url: "https://www.codechef.com/problems/FLOW008",
		difficulty: "beginner",
		tags: ["conditionals"],
		rating: 800,
	},
	{
		title: "Gross Salary",
		platform: "codechef",
		problemId: "FLOW011",
		url: "https://www.codechef.com/problems/FLOW011",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "The Smallest Pair",
		platform: "codechef",
		problemId: "SMPAIR",
		url: "https://www.codechef.com/problems/SMPAIR",
		difficulty: "beginner",
		tags: ["sorting"],
		rating: 900,
	},
	{
		title: "Courses in an University",
		platform: "codechef",
		problemId: "CCOURSES",
		url: "https://www.codechef.com/problems/CCOURSES",
		difficulty: "easy",
		tags: ["greedy"],
		rating: 1100,
	},
	{
		title: "Match Sticks",
		platform: "codechef",
		problemId: "MATCHES",
		url: "https://www.codechef.com/problems/MATCHES",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Chef and Remissness",
		platform: "codechef",
		problemId: "REMISS",
		url: "https://www.codechef.com/problems/REMISS",
		difficulty: "beginner",
		tags: ["basic-programming", "math"],
		rating: 900,
	},
	{
		title: "GCD and LCM",
		platform: "codechef",
		problemId: "FLOW016",
		url: "https://www.codechef.com/problems/FLOW016",
		difficulty: "beginner",
		tags: ["gcd", "math"],
		rating: 900,
	},
	{
		title: "Sum OR Difference",
		platform: "codechef",
		problemId: "DIFFSUM",
		url: "https://www.codechef.com/problems/DIFFSUM",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Chef and Netflix",
		platform: "codechef",
		problemId: "NETFLIX",
		url: "https://www.codechef.com/problems/NETFLIX",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Finding Square Roots",
		platform: "codechef",
		problemId: "FSQRT",
		url: "https://www.codechef.com/problems/FSQRT",
		difficulty: "beginner",
		tags: ["basic-programming", "math"],
		rating: 800,
	},
	{
		title: "Count Divisors",
		platform: "codechef",
		problemId: "COONDIV",
		url: "https://www.codechef.com/problems/COONDIV",
		difficulty: "beginner",
		tags: ["number-theory"],
		rating: 900,
	},
	{
		title: "Puppy and Sum",
		platform: "codechef",
		problemId: "PPSUM",
		url: "https://www.codechef.com/problems/PPSUM",
		difficulty: "beginner",
		tags: ["math"],
		rating: 900,
	},
	{
		title: "Mahasena",
		platform: "codechef",
		problemId: "AMR15A",
		url: "https://www.codechef.com/problems/AMR15A",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Chef and his Students",
		platform: "codechef",
		problemId: "CHSTUD",
		url: "https://www.codechef.com/problems/CHSTUD",
		difficulty: "beginner",
		tags: ["strings"],
		rating: 900,
	},
	{
		title: "Bear and Segment 01",
		platform: "codechef",
		problemId: "SEGM01",
		url: "https://www.codechef.com/problems/SEGM01",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 900,
	},
	{
		title: "Chef and Rainbow Array",
		platform: "codechef",
		problemId: "RAINBOWA",
		url: "https://www.codechef.com/problems/RAINBOWA",
		difficulty: "easy",
		tags: ["arrays"],
		rating: 1000,
	},
	{
		title: "Chef and Masks",
		platform: "codechef",
		problemId: "CHFMASK",
		url: "https://www.codechef.com/problems/CHFMASK",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Magician versus Chef",
		platform: "codechef",
		problemId: "CHEFINSQ",
		url: "https://www.codechef.com/problems/CHEFINSQ",
		difficulty: "easy",
		tags: ["combinatorics"],
		rating: 1200,
	},
	{
		title: "The Block Game",
		platform: "codechef",
		problemId: "PALL01",
		url: "https://www.codechef.com/problems/PALL01",
		difficulty: "beginner",
		tags: ["strings"],
		rating: 800,
	},
	{
		title: "Cricket Match",
		platform: "codechef",
		problemId: "CRICMATCH",
		url: "https://www.codechef.com/problems/CRICMATCH",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Farmer And His Plot",
		platform: "codechef",
		problemId: "AMMEAT",
		url: "https://www.codechef.com/problems/AMMEAT",
		difficulty: "easy",
		tags: ["greedy", "sorting"],
		rating: 1100,
	},
	{
		title: "Chef and Easy Problem",
		platform: "codechef",
		problemId: "CHEFEZQ",
		url: "https://www.codechef.com/problems/CHEFEZQ",
		difficulty: "easy",
		tags: ["greedy"],
		rating: 1000,
	},
	{
		title: "Chef and String",
		platform: "codechef",
		problemId: "CHEFSTR1",
		url: "https://www.codechef.com/problems/CHEFSTR1",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 900,
	},
	{
		title: "Enormous Eat Input",
		platform: "codechef",
		problemId: "EATIN",
		url: "https://www.codechef.com/problems/EATIN",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Richie Rich",
		platform: "codechef",
		problemId: "PLAYFIT",
		url: "https://www.codechef.com/problems/PLAYFIT",
		difficulty: "beginner",
		tags: ["greedy"],
		rating: 900,
	},
	{
		title: "Chef and Demonetization",
		platform: "codechef",
		problemId: "DEMORGAN",
		url: "https://www.codechef.com/problems/DEMORGAN",
		difficulty: "easy",
		tags: ["greedy", "math"],
		rating: 1100,
	},
	{
		title: "Football",
		platform: "codechef",
		problemId: "FOOTBALL",
		url: "https://www.codechef.com/problems/FOOTBALL",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "The Mango Truck",
		platform: "codechef",
		problemId: "MFREQ",
		url: "https://www.codechef.com/problems/MFREQ",
		difficulty: "easy",
		tags: ["frequency-counting"],
		rating: 1000,
	},
	{
		title: "Encode The String",
		platform: "codechef",
		problemId: "ENCSTR",
		url: "https://www.codechef.com/problems/ENCSTR",
		difficulty: "easy",
		tags: ["strings"],
		rating: 1000,
	},
	{
		title: "Chef and Dice",
		platform: "codechef",
		problemId: "CHEFDICE",
		url: "https://www.codechef.com/problems/CHEFDICE",
		difficulty: "easy",
		tags: ["math"],
		rating: 1100,
	},
	{
		title: "Sticks",
		platform: "codechef",
		problemId: "STICKS",
		url: "https://www.codechef.com/problems/STICKS",
		difficulty: "beginner",
		tags: ["greedy", "sorting"],
		rating: 900,
	},
	{
		title: "Good Program",
		platform: "codechef",
		problemId: "GOODPROG",
		url: "https://www.codechef.com/problems/GOODPROG",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Tom and Jerry",
		platform: "codechef",
		problemId: "Crelativs",
		url: "https://www.codechef.com/problems/Crelativs",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Chef and Two Strings",
		platform: "codechef",
		problemId: "CHEFTWO",
		url: "https://www.codechef.com/problems/CHEFTWO",
		difficulty: "beginner",
		tags: ["strings"],
		rating: 900,
	},
	{
		title: "Tanu and Head-bob",
		platform: "codechef",
		problemId: "HEADBOB",
		url: "https://www.codechef.com/problems/HEADBOB",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Judging Delay",
		platform: "codechef",
		problemId: "SLOWSOLN",
		url: "https://www.codechef.com/problems/SLOWSOLN",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Finding Shoes",
		platform: "codechef",
		problemId: "SHOES",
		url: "https://www.codechef.com/problems/SHOES",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
	{
		title: "Pawri Meme",
		platform: "codechef",
		problemId: "PAWRI",
		url: "https://www.codechef.com/problems/PAWRI",
		difficulty: "beginner",
		tags: ["strings"],
		rating: 900,
	},
	{
		title: "COVID Pandemic and Long Queue",
		platform: "codechef",
		problemId: "LONGQUEUE",
		url: "https://www.codechef.com/problems/LONGQUEUE",
		difficulty: "beginner",
		tags: ["basic-programming"],
		rating: 800,
	},
];

async function seedProblems() {
	try {
		// Connect to MongoDB
		await mongoose.connect(process.env.MONGODB_URI);
		console.log("Connected to MongoDB");

		// Find admin user
		const admin = await User.findOne({ role: "admin" });
		if (!admin) {
			console.error("Admin user not found. Please create an admin user first.");
			process.exit(1);
		}

		console.log(`Found admin user: ${admin.username}`);

		// Delete existing global problems to avoid duplicates
		await Problem.deleteMany({ isGlobal: true });
		console.log("Cleared existing global problems");

		// Insert problems
		const problems = problemsData.map((problem) => ({
			...problem,
			userId: admin._id,
			isGlobal: true,
			createdByAdmin: true,
			approvalStatus: "approved",
			status: "todo",
			approvedBy: admin._id,
			approvedAt: new Date(),
		}));

		await Problem.insertMany(problems);
		console.log(`Successfully seeded ${problems.length} problems!`);
		console.log(
			`- LeetCode: ${problems.filter((p) => p.platform === "leetcode").length}`
		);
		console.log(
			`- Codeforces: ${
				problems.filter((p) => p.platform === "codeforces").length
			}`
		);
		console.log(
			`- CodeChef: ${problems.filter((p) => p.platform === "codechef").length}`
		);

		process.exit(0);
	} catch (error) {
		console.error("Error seeding problems:", error);
		process.exit(1);
	}
}

seedProblems();
